### PR TITLE
config: let user specify an alternate endpoint

### PR DESCRIPTION
**Pull request by tapas-saha**
Refer to the description of the issue https://github.com/logdna/fluent-plugin-logdna/issues/31 for details about why this change is needed.

Please review and merge.

### CODE REVIEW

**Review by jakedipity — DISMISSED** [review]
Looks good to me

**Review by matt-march — COMMENTED** [review]
Thanks @tapas-saha! Change looks good, but would you mind adding a test case that covers this parameter? 

Existing tests are under `test/plugin/test_out_logdna.rb` and for now can be run with (for example):

```
ruby test/plugin/*.rb
```

@smusali is awesome and is working on adding a CI workflow that also runs them in #30.

**Comment by tapas-saha** [comment]
> Thanks @tapas-saha! Change looks good, but would you mind adding a test case that covers this parameter?
> 
> Existing tests are under `test/plugin/test_out_logdna.rb` and for now can be run with (for example):
> 
> ```
> ruby test/plugin/*.rb
> ```
> 
> @smusali is awesome and is working on adding a CI workflow that also runs them in #30.

@matt-march Done. I added coverages under two existing `configuration` tests. Below is the test result screenshot from my setup.
image

**Review by smusali — APPROVED** [review]

**Review by matt-march — APPROVED** [review]
Thanks @tapas-saha! I appreciate you adding tests for this too.

**Comment by tapas-saha** [comment]
Thanks, @matt-march @smusali and @jakedipity for your reviews and approvals. Could anyone of you please merge it?

**Pull request merged**
